### ISSUE TITLE
Koodikatselmointi II

### ISSUE THREAD

**Issue by mipyykko** [luupanu/Skrapple#1]
Ladattu 19.2. klo 22:30

Codebase näyttää hyvin organisoidulta ja rakenne on selkeä. Toiminta on helppo ymmärtää jo pelkästään koodia lukemalla mutta kommentitkin ovat hyvin kuvaavia. Perintää käytetty myös mallikkaasti. Testit ovat myös tarpeeksi kattavat joten ei nipotettavaa niistäkään. 

Peli on toki ilmiselvästi vielä kehitysvaiheessa, esim. siirtoja ei voi tehdä, mutta koodia tutkimalla eipä sellaista ominaisuutta ole vielä koodattukaan. Runko on kuitenkin hyvällä mallilla ja siihen on helppo pultata lisäosia.

**Comment by luupanu** [comment]
Kiitos palautteesta! :)
